
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Function to generate a random reading time string
const generateReadTime = () => {
  const minutes = Math.floor(Math.random() * 8) + 2; // Random between 2-10 minutes
  return `${minutes} min read`;
};

// Function to generate a random date within the last 14 days
const generateRecentDate = () => {
  const now = new Date();
  const daysAgo = Math.floor(Math.random() * 14); // Random between 0-14 days ago
  now.setDate(now.getDate() - daysAgo);
  return now.toISOString();
};

// List of potential news sources
const newsSources = [
  "The Hindu",
  "Indian Express",
  "Times of India",
  "Krishi Jagran",
  "DD Kisan",
  "Rural Voice",
  "ICAR News",
  "AgriTimes",
  "Farm & Food",
  "Agriculture Today",
];

// Function to generate news content based on category
const generateNewsForCategory = (category: string, count: number = 15) => {
  const categoryTitles: Record<string, string[]> = {
    "general_agriculture": [
      "Government launches new agricultural policy to boost crop production",
      "Indian farmers embrace digital technologies for better farm management",
      "National agricultural output increases by 4.5% in 2024",
      "New sustainable farming practices gain traction across rural India",
      "Agricultural universities see record enrollment for 2024 academic year",
      "Farm mechanization drives 15% increase in crop yield this season",
      "Rural employment scheme expands to cover agricultural laborers",
      "National food security mission achieves milestone in staple crop production",
      "Agricultural cooperative movement strengthens in southern states",
      "Climate-resilient farming methods show promising results in field trials",
      "Agriculture ministry announces new subsidy scheme for small farmers",
      "Indian agricultural exports reach all-time high in Q2 2024",
      "Farmers' producer organizations report record growth this financial year",
      "Sustainable water management transforms drought-prone regions",
      "Government launches mobile app for real-time agricultural advisories",
      "Agricultural census reveals changing patterns in land holdings",
      "Traditional farming knowledge integrated into modern agricultural practices",
      "National agricultural innovation fund supports 200 new startups",
      "Crop insurance scheme reaches 70% of eligible farmers this season",
      "Agricultural waste management initiatives reduce carbon footprint",
    ],
    "crop_production": [
      "Record wheat harvest expected this Rabi season across North India",
      "New rice variety shows 30% higher yield in field trials",
      "Millet production doubles as government promotes nutritional security",
      "Cotton farmers adopt organic practices to meet international demand",
      "Pulse crop output increases after successful pest management",
      "Sugarcane farmers implement water-saving techniques to boost yields",
      "Oilseed production rises as government promotes self-sufficiency",
      "Fruit crop damage minimized through early weather warning systems",
      "New sunflower hybrid performs well in semi-arid regions",
      "Maize productivity increases with adoption of precision farming",
      "Tea plantations in Northeast implement sustainable practices",
      "Soybean farmers report bumper harvest after adopting new varieties",
      "Potato production rises with improved storage facilities",
      "Vegetable farmers increase income through protected cultivation",
      "High-density apple orchards transform horticulture in Himalayan states",
      "Spice crops fetch record prices as export demand increases",
      "Floriculture sector blooms with new greenhouse technology",
      "Coffee plantations implement shade-growing for premium quality",
      "Jute cultivation revives as demand for natural fibers increases",
      "Coconut farmers diversify products to increase market value",
    ],
    "agritech": [
      "Drone technology revolutionizes precision farming in Indian agriculture",
      "AI-powered soil testing kit developed by Indian agritech startup",
      "Smartphone app helps farmers diagnose crop diseases instantly",
      "IoT sensors optimize irrigation in water-scarce agricultural regions",
      "Blockchain technology ensures transparency in agricultural supply chain",
      "Solar-powered cold storage solutions reduce post-harvest losses",
      "Machine learning models predict crop yields with 90% accuracy",
      "Digital marketplace connects farmers directly to consumers",
      "Smart tractors with GPS-guided systems gain popularity",
      "Vertical farming startups attract major investment in urban centers",
      "Satellite imagery helps farmers make data-driven decisions",
      "Robotics technology addresses labor shortage in agriculture sector",
      "Hydroponic systems enable year-round vegetable production",
      "Climate-smart technology helps farmers adapt to changing weather patterns",
      "Mobile weather stations provide hyperlocal forecasts to farmers",
      "Digital lending platforms simplify agricultural credit for small farmers",
      "Agricultural chatbots offer 24/7 advisory services in local languages",
      "Precision fertilizer applicators reduce input costs for farmers",
      "Smart greenhouse technology optimizes plant growth conditions",
      "Farm management software helps track agricultural operations efficiently",
    ],
    "market_prices": [
      "Vegetable prices stabilize after government market intervention",
      "Rice exports fetch premium prices in international markets",
      "Onion prices rise due to reduced harvest in major producing states",
      "Pulses see price correction after bumper harvest this season",
      "Spice market reports steady growth in export and domestic sectors",
      "Fruit prices fluctuate due to weather disruptions in key growing regions",
      "Wheat procurement at MSP benefits farmers across northern plains",
      "Cotton prices improve as textile industry demand increases",
      "Oilseed market responds positively to new export opportunities",
      "Sugar prices remain stable despite fluctuations in production",
      "Potato farmers receive better returns through direct marketing",
      "Tea auctions report increased buyer participation and better prices",
      "Maize prices strengthen as poultry feed demand grows",
      "Coffee growers see improved profits from specialty market demand",
      "Milk procurement prices increase benefiting dairy farmers",
      "Flower market recovers as wedding season demand picks up",
      "Jaggery prices remain firm in rural markets across India",
      "Organic produce commands 30% premium in urban markets",
      "Cashew nut prices improve after processing sector expansion",
      "Mango exports open new price discovery channels for growers",
    ],
    "climate_updates": [
      "Monsoon forecast predicts normal rainfall for agricultural regions",
      "Heat wave alert issued for northern wheat-growing states",
      "Early warning system helps farmers prepare for extreme weather events",
      "Climate-resilient crop varieties show promising results in drought conditions",
      "Flood mitigation measures protect farmlands in low-lying areas",
      "Weather patterns show significant shift in traditional growing seasons",
      "Frost protection advisories issued for horticultural regions",
      "Long-range forecast suggests favorable conditions for Rabi crops",
      "Agricultural meteorological stations expanded to cover more districts",
      "Climate change impacts yield variations in rain-fed agricultural zones",
      "Hailstorm damage assessment system implemented for insurance claims",
      "Cyclone early warning helps coastal farmers secure crops in time",
      "Heat stress monitoring system guides irrigation scheduling",
      "Winter conditions favorable for wheat development in North India",
      "Agro-climatic zone mapping updated to reflect changing patterns",
      "Weather-based crop advisory system reaches 60% of farming population",
      "Dry spell mitigation strategies shared with farmers in vulnerable regions",
      "Phenological calendar adjusted to align with climate shifts",
      "Remote sensing data helps assess moisture stress in standing crops",
      "Temperature anomalies tracked to guide agricultural planning",
    ],
    "government_schemes": [
      "PM Kisan scheme releases 16th installment benefiting 10 crore farmers",
      "Soil health card scheme enters new phase with advanced testing parameters",
      "E-NAM platform expands to include 1000 agricultural markets nationwide",
      "Pradhan Mantri Fasal Bima Yojana covers record crop area this season",
      "Agricultural infrastructure fund approves projects worth ₹10,000 crore",
      "Kisan Credit Card scheme simplifies renewal process for farmers",
      "Organic farming certification subsidy increases to 90% for small farmers",
      "New scheme launched to promote natural farming across India",
      "Government extends procurement operations to additional crops",
      "Micro-irrigation subsidy scheme achieves 5 million hectare coverage",
      "Farmer producer organization policy revised with increased support",
      "Agricultural mechanization scheme includes custom hiring centers",
      "Post-harvest management gets boost with new processing infrastructure scheme",
      "Agri-clinic and agri-business scheme creates rural entrepreneurship",
      "Livestock insurance scheme coverage expanded to additional species",
      "Beekeeping initiative under ATMA scheme shows remarkable progress",
      "Rural godown scheme revised to address storage infrastructure gap",
      "Marketing infrastructure scheme funds 500 new rural markets",
      "Integrated scheme for agricultural marketing improves value chain",
      "Sub-mission on agricultural mechanization reaches tribal areas",
    ],
    "farmer_stories": [
      "Progressive farmer from Tamil Nadu wins national award for innovative practices",
      "Women farmers' collective transforms village economy in Rajasthan",
      "Tribal farmers in Northeast adopt agroforestry with remarkable success",
      "Young agricultural entrepreneur's startup creates rural employment",
      "Veteran farmer mentors youth to adopt sustainable farming techniques",
      "Farmer from water-scarce region develops innovative irrigation method",
      "Organic farming transforms fortunes of small farmer collective in Kerala",
      "Widow farmers' self-help group achieves financial independence",
      "Marginal farmer increases income through integrated farming system",
      "Traditional seed keeper preserves indigenous varieties for future generations",
      "Farmer-scientist partnership develops location-specific farming solutions",
      "Rural innovation by farmer solves post-harvest challenges locally",
      "Farmer's market initiative connects producers directly with urban consumers",
      "Agricultural influencer educates farmers through social media platforms",
      "Disabled farmer overcomes challenges to become village mentor",
      "Landless agricultural laborers form cooperative for economic empowerment",
      "Millennial returns to village to transform family farm into agribusiness",
      "Farmer-led watershed development transforms drought-prone region",
      "Community supported agriculture model succeeds in peri-urban area",
      "Indigenous knowledge keeper integrates traditional practices with modern techniques",
    ],
    "agricultural_exports": [
      "India's agricultural exports cross $50 billion mark for first time",
      "Basmati rice exports to Middle East increase by 25% this fiscal",
      "Organic food exports see significant growth in European markets",
      "Indian spices gain new markets in Latin America and Africa",
      "GI-tagged agricultural products command premium in international markets",
      "Mango varieties from India enter new international destinations",
      "Buffalo meat exports recover after pandemic-related disruptions",
      "Marine products export reaches all-time high with value addition focus",
      "Agricultural and Processed Food Export Development Authority sets new targets",
      "Non-basmati rice shipments grow despite export restrictions",
      "Fresh fruit exports benefit from improved cold chain logistics",
      "Cereal exports diversify beyond traditional markets",
      "India becomes leading exporter of specific spice varieties globally",
      "Dairy product exports increase with new quality certifications",
      "Tea exports benefit from increased demand for specialty varieties",
      "Agricultural export zones show increased outbound shipments",
      "Honey exports double after quality protocols implementation",
      "Natural food coloring exports benefit from clean label movement",
      "Seeds export program opens new revenue streams for producers",
      "Export promotion schemes benefit small and medium agribusinesses",
    ],
    "rural_development": [
      "Rural road connectivity program reaches 95% of targeted villages",
      "Digital literacy campaign transforms information access in rural areas",
      "Self-help groups generate record income through agricultural activities",
      "Rural entrepreneurship program creates 100,000 new enterprises",
      "Village adoption scheme shows transformative results in pilot areas",
      "Rural housing scheme completes 10 million houses milestone",
      "Clean energy initiatives benefit agricultural processing in villages",
      "Water conservation structures transform groundwater levels in rural watersheds",
      "Rural health infrastructure improves with mobile medical units for remote areas",
      "Village knowledge centers boost agricultural information dissemination",
      "Rural sanitation campaign achieves open defecation free status in new districts",
      "Financial inclusion reaches 90% of rural households through banking services",
      "Women's empowerment through agricultural skilling programs shows results",
      "Rural tourism linked with agricultural experiences generates additional income",
      "Digital service centers in villages simplify access to government programs",
      "Rural artisans find new markets through e-commerce platforms",
      "Community managed natural resource initiatives show sustainable outcomes",
      "Rural sports infrastructure development nurtures young talent",
      "Traditional crafts linked with agricultural byproducts create employment",
      "Rural technology hubs connect villages to knowledge resources",
    ],
    "organic_farming": [
      "Organic farming area in India expands by 25% in past year",
      "Sikkim's organic farming model replicated in other Himalayan states",
      "Natural farming practices reduce input costs for small farmers",
      "Organic certification process simplified for farmer groups",
      "Market linkages for organic produce strengthen with dedicated supply chains",
      "Organic farming training programs reach 100,000 farmers nationwide",
      "Zero budget natural farming shows promising results in rain-fed areas",
      "Indigenous microorganisms improve soil health in organic systems",
      "Organic villages initiative creates chemical-free agricultural zones",
      "Participatory guarantee system makes organic certification accessible",
      "Research documents biodiversity improvement in organic farming areas",
      "Traditional knowledge of organic practices documented and shared",
      "Urban demand for organic produce creates premium market opportunities",
      "Organic seed production networks establish self-sufficiency",
      "Integrated organic farming systems optimize resource utilization",
      "Organic farmers' markets establish direct consumer connections",
      "Organic input production units setup at panchayat level",
      "Export demand for certified organic products continues to grow",
      "Organic farming adoption addresses soil health concerns",
      "Training modules on organic farming translated into regional languages",
    ],
    "farm_mechanization": [
      "Custom hiring centers for farm machinery reach every district",
      "Small farm mechanization tools developed for hilly terrain",
      "Solar-powered agricultural equipment gains popularity in field operations",
      "Women-friendly farm tools address ergonomic challenges in agriculture",
      "Drone adoption for agricultural operations expands with regulatory support",
      "Precision planting equipment improves seed placement and germination",
      "Harvester modifications address crop residue management challenges",
      "Farm mechanization subsidy utilization reaches record levels this year",
      "Locally manufactured agricultural tools reduce equipment costs",
      "Multi-crop planters and harvesters gain popularity among farmers",
      "Mechanized transplanting of rice reduces labor requirements",
      "Post-harvest mechanization reduces grain losses significantly",
      "Small tractors designed for marginal landholdings increase efficiency",
      "Digital platforms for machinery rental transform access in rural areas",
      "Training programs on equipment maintenance reach grassroot mechanics",
      "Laser land leveling technology adoption improves water use efficiency",
      "Machinery banks established at farmer producer organization level",
      "Indigenous innovation in farm tools addresses local agricultural needs",
      "Fruit harvesting equipment reduces damage and improves quality",
      "Virtual reality training modules prepare operators for complex machinery",
    ],
    "agriculture_education": [
      "Agricultural universities revamp curriculum to include emerging technologies",
      "Vocational agriculture courses see increased enrollment across rural areas",
      "Krishi Vigyan Kendras train record number of farmers in new techniques",
      "Digital learning platforms make agricultural education accessible remotely",
      "School garden programs introduce students to sustainable farming practices",
      "Agricultural apprenticeship program connects graduates with progressive farms",
      "International collaboration strengthens agricultural research and education",
      "Industry-academia partnerships create employment pathways for agri-graduates",
      "Farmers' field schools demonstrate improved practices in villages",
      "Agri-clinics established by agricultural graduates provide knowledge services",
      "Mobile agricultural extension classrooms reach remote farming communities",
      "Skill certification programs validate traditional agricultural knowledge",
      "Agricultural hackathons engage youth in solving farming challenges",
      "Rural agricultural libraries expand digital resources for farmers",
      "Training of trainers program creates master farmers as local educators",
      "Agri-business education programs nurture rural entrepreneurship",
      "Distance learning programs in agriculture reach working professionals",
      "Farmer-scientist interaction platforms facilitate knowledge exchange",
      "Agricultural podcasts in regional languages gain rural listeners",
      "Specialized training centers focus on emerging agricultural sectors",
    ],
    "livestock_farming": [
      "Indigenous cattle breeding program preserves native genetic resources",
      "Dairy cooperatives expand collection network in underserved areas",
      "Poultry farming models developed for landless agricultural laborers",
      "Goat farming initiatives transform livelihoods in drought-prone regions",
      "Animal health cards implemented for livestock monitoring and management",
      "Fodder development program addresses nutritional challenges in livestock",
      "Backyard poultry initiatives improve protein nutrition in rural households",
      "Veterinary telemedicine services reach remote pastoral communities",
      "Sheep wool quality improvement program benefits traditional herders",
      "Indigenous poultry breeds conservation program gains momentum",
      "Camel dairy initiatives create new livelihood opportunities in arid regions",
      "Pig farming enterprises show success in tribal areas with training support",
      "Mobile veterinary units extend coverage to remote livestock rearing areas",
      "Fish farming in farm ponds demonstrates integrated livelihood model",
      "Vaccine delivery system strengthened for livestock disease prevention",
      "Breeding records digitization helps maintain genetic improvement data",
      "Silage making technologies adopted for year-round fodder availability",
      "Quality milk production initiatives improve dairy farm economics",
      "Waste to wealth models convert livestock waste to valuable byproducts",
      "Heat stress management protocols developed for livestock protection",
    ],
    "irrigation_news": [
      "Micro-irrigation coverage expands to 50% of targeted area nationwide",
      "Canal modernization project improves water use efficiency in command areas",
      "Participatory irrigation management transforms water distribution equity",
      "Water user associations take charge of irrigation scheduling in projects",
      "Irrigation infrastructure gets investment boost through special package",
      "Sensor-based irrigation systems reduce water consumption by 30%",
      "River linking project progresses to address regional water imbalances",
      "Check dam construction drive completes 10,000 structures this year",
      "Farm pond program creates water security for rain-fed agriculture",
      "Solar pumping systems replace diesel pumps in major irrigation initiative",
      "Water budgeting app helps farmers optimize irrigation scheduling",
      "Traditional water harvesting structures revitalized through community efforts",
      "Drip irrigation for sugarcane reduces water usage while improving yields",
      "Irrigation pipeline networks replace open channels to minimize losses",
      "Watershed development shows remarkable groundwater improvement",
      "Treated wastewater utilized for peri-urban agricultural irrigation",
      "Sprinkler systems adoption increases in water-scarce regions",
      "Canal automation technology improves distribution efficiency",
      "Rainwater harvesting structures mandatory for farm infrastructure support",
      "Groundwater recharge initiatives show positive results in over-exploited areas",
    ],
    "agricultural_research": [
      "Gene editing breakthrough improves rice drought tolerance significantly",
      "Indian Agricultural Research Institute releases 10 new crop varieties",
      "Climate-resilient crop varieties developed through participatory breeding",
      "Research on nano-fertilizers shows promising results in field trials",
      "Biological control agents reduce pesticide use in major crops",
      "Genomic selection accelerates livestock breeding progress",
      "Conservation agriculture research documents long-term soil health benefits",
      "Crop modeling helps predict yield under changing climate scenarios",
      "Integrated pest management strategies developed for emerging pests",
      "Nutrition-sensitive agriculture research focuses on biofortified crops",
      "Indigenous technical knowledge validated through scientific studies",
      "Plant growth promoting rhizobacteria improve nutrient use efficiency",
      "Post-harvest processing research reduces food waste significantly",
      "Phenomics facilities accelerate crop improvement research",
      "Agri-waste utilization research creates valuable byproducts",
      "Salt-tolerant crop varieties show promise for coastal agricultural areas",
      "Drought-escaping crop varieties minimize climate risk for farmers",
      "Agricultural biotechnology research focuses on reducing input requirements",
      "Precision agriculture research optimizes resource use in farming",
      "Crop wild relatives provide valuable traits for breeding programs",
    ],
  };

  const categorySummaries: Record<string, string[]> = {
    "general_agriculture": [
      "The government has launched a comprehensive agricultural policy aimed at boosting crop production across all states. The policy includes subsidies for seeds, fertilizers, and modern farming equipment.",
      "Indian farmers are increasingly adopting digital technologies to improve farm management. Mobile apps for weather forecasting, soil health monitoring, and market prices are gaining popularity.",
      "India's national agricultural output has increased by 4.5% in 2024, surpassing expectations despite climate challenges. Rice and wheat production showed the most significant improvements.",
      "Sustainable farming practices including conservation agriculture and agroforestry are gaining traction across rural India, with over 2 million farmers adopting these methods in the past year.",
      "Agricultural universities across India report record enrollment for the 2024 academic year, with specialized programs in agritech and sustainable agriculture seeing the highest demand.",
      "Farm mechanization has driven a 15% increase in crop yield this season, with small and marginal farmers benefiting from custom hiring centers for agricultural machinery.",
      "The rural employment scheme has been expanded to specifically cover agricultural laborers during non-farming seasons, providing year-round income opportunities in rural areas.",
      "The National Food Security Mission has achieved a major milestone in increasing production of staple crops, with pulses and oilseeds seeing the most significant improvements.",
      "The agricultural cooperative movement is gaining strength in southern states, with new models of farmer producer organizations showing promising results for smallholder farmers.",
      "Climate-resilient farming methods developed by agricultural research institutions are showing promising results in field trials, with drought-tolerant varieties performing particularly well.",
      "The Agriculture Ministry has announced a new subsidy scheme specifically targeting small farmers with holdings below 2 hectares, aiming to increase their access to modern farming inputs.",
      "Indian agricultural exports have reached an all-time high in Q2 2024, with basmati rice, spices, and fresh fruits being the top contributors to this growth.",
      "Farmers' producer organizations across India report record growth this financial year, with over 5,000 new FPOs registered and accessing institutional credit facilities.",
      "Sustainable water management technologies have transformed agricultural prospects in traditionally drought-prone regions, with water harvesting structures benefiting over 3 million hectares.",
      "The government has launched a comprehensive mobile app providing real-time agricultural advisories on weather, market prices, pest management, and crop-specific recommendations.",
      "The latest agricultural census reveals changing patterns in land holdings, with a notable increase in women landowners and a decrease in the average farm size across most states.",
      "Traditional farming knowledge is being systematically documented and integrated into modern agricultural practices, with particular focus on organic pest management techniques.",
      "The National Agricultural Innovation Fund has supported 200 new startups working on solutions ranging from precision farming to post-harvest technologies.",
      "The government crop insurance scheme has reached 70% of eligible farmers this season, providing coverage against natural calamities and pest outbreaks across major agricultural regions.",
      "Agricultural waste management initiatives implemented across farming communities have significantly reduced the carbon footprint of crop production while improving soil health.",
    ],
    "crop_production": [
      "A record wheat harvest is expected this Rabi season across North India, with favorable weather conditions and increased area under improved varieties contributing to the bumper crop.",
      "A new rice variety developed by agricultural scientists shows 30% higher yield in extensive field trials across different agro-climatic zones, while requiring less water than conventional varieties.",
      "Millet production has doubled in the past year as the government actively promotes these nutritious grains for food security and farmer income. International demand is also increasing steadily.",
      "Cotton farmers across Maharashtra and Gujarat are increasingly adopting organic practices to meet growing international demand for chemical-free cotton. Premium prices are driving this transition.",
      "Pulse crop output has increased significantly after the successful implementation of integrated pest management practices, addressing the longstanding yield gap in these protein-rich crops.",
      "Sugarcane farmers in major producing states have implemented drip irrigation and trash mulching techniques, resulting in water savings of up to 40% while boosting yields.",
      "Oilseed production has risen by 15% as the government promotes self-sufficiency in edible oils. Improved varieties and better agronomic practices have contributed to this improvement.",
      "Fruit crop damage from unseasonal rains has been minimized through early weather warning systems that allow farmers to take protective measures for vulnerable orchards.",
      "A new sunflower hybrid specially developed for semi-arid regions is performing exceptionally well in field trials, offering a viable crop option for farmers in low-rainfall areas.",
      "Maize productivity has increased substantially with the adoption of precision farming techniques including optimal plant population, balanced nutrition, and timely weed management.",
      "Tea plantations in the Northeast have implemented sustainable practices including organic cultivation and rainwater harvesting, improving both yield quality and environmental performance.",
      "Soybean farmers report a bumper harvest this season after adopting new varieties resistant to yellow mosaic virus, a major disease that previously caused significant yield losses.",
      "Potato production has risen by 25% with the establishment of improved storage facilities that reduce post-harvest losses and allow farmers to sell their produce when market prices are favorable.",
      "Vegetable farmers have increased their income by 35% through protected cultivation techniques including poly houses and shade nets, enabling off-season production of high-value crops.",
      "High-density apple orchards using dwarf varieties have transformed horticulture in Himalayan states, with yields three times higher than traditional orchards while using less land area.",
      "Spice crops are fetching record prices as export demand increases for Indian turmeric, cumin, and black pepper. Farmers are expanding cultivation area in response to favorable market conditions.",
      "The floriculture sector is blooming with the adoption of new greenhouse technology that enables precise control of growing conditions, resulting in higher quality flowers for domestic and export markets.",
      "Coffee plantations in South India are implementing shade-growing techniques that produce premium quality beans while preserving biodiversity and providing additional income from shade trees.",
      "Jute cultivation is experiencing a revival as demand for natural fibers increases globally. Improved retting techniques are helping farmers produce better quality fiber that commands higher prices.",
      "Coconut farmers are diversifying into value-added products such as virgin coconut oil, coconut sugar, and coir products, significantly increasing returns from their plantations.",
    ],
    "agritech": [
      "Drone technology is revolutionizing precision farming in Indian agriculture, with capabilities for crop spraying, health monitoring, and yield estimation transforming farm management practices.",
      "An AI-powered soil testing kit developed by an Indian agritech startup delivers results in 30 minutes, analyzing 16 parameters including macro and micronutrients at an affordable cost for farmers.",
      "A new smartphone app using machine learning allows farmers to diagnose crop diseases instantly by simply taking a photo, providing immediate management recommendations in 12 regional languages.",
      "IoT sensors being deployed across agricultural regions are optimizing irrigation by monitoring soil moisture in real-time, reducing water usage by up to 50% while improving crop health.",
      "Blockchain technology implementation in agricultural supply chains is ensuring transparency from farm to fork, with consumers able to trace produce origin and farmers receiving fair compensation.",
      "Solar-powered cold storage solutions designed specifically for rural areas are reducing post-harvest losses by up to 30%, extending the shelf life of perishable produce for small farmers.",
      "Machine learning models developed by Indian researchers can now predict crop yields with 90% accuracy three months before harvest by analyzing satellite imagery and weather data patterns.",
      "Digital marketplaces connecting farmers directly to consumers have expanded to 500 districts, eliminating intermediaries and increasing farmer profits by 25-40% across various commodities.",
      "Smart tractors equipped with GPS-guided systems for precision operations are gaining popularity, with custom hiring centers making this technology accessible to small and marginal farmers.",
      "Vertical farming startups in urban centers have attracted investment worth ₹500 crore, producing leafy greens and herbs year-round while using 95% less water than conventional farming.",
      "Satellite imagery analysis is helping farmers make data-driven decisions by providing actionable insights on crop health, pest infestation, and optimal harvesting time across large areas.",
      "Robotics technology is addressing the agricultural labor shortage with machines capable of transplanting rice seedlings five times faster than manual operations, reducing dependence on seasonal workers.",
      "Hydroponic systems enable year-round vegetable production regardless of outdoor conditions, with urban farms supplying fresh produce to city markets with minimal transportation footprint.",
      "Climate-smart technology packages combining weather forecasts, crop advisories, and risk management tools are helping farmers adapt to increasingly unpredictable weather patterns.",
      "Mobile weather stations installed across agricultural regions provide hyperlocal forecasts to farmers, allowing for timely field operations and protective measures against adverse conditions.",
      "Digital lending platforms have simplified agricultural credit for small farmers by using alternative data for risk assessment, reaching previously underserved farming communities with customized loan products.",
      "Agricultural chatbots offering 24/7 advisory services in local languages have reached 5 million farmers, answering queries on crop management, pest control, and market information instantly.",
      "Precision fertilizer applicators that adjust nutrient delivery based on soil variation are reducing input costs for farmers by 15-20% while minimizing environmental impact from excess application.",
      "Smart greenhouse technology that automatically adjusts temperature, humidity, and light conditions is optimizing plant growth in controlled environments, yielding premium-quality produce year-round.",
      "Farm management software solutions help track agricultural operations efficiently, with mobile apps allowing farmers to record inputs, activities, and harvests while maintaining digital records for certification.",
    ],
    "market_prices": [
      "Vegetable prices have stabilized after the government's market intervention through increased procurement operations at minimum support prices, benefiting both farmers and consumers.",
      "Indian rice exports are fetching premium prices in international markets due to their superior quality and the global food security concerns, with basmati varieties seeing the highest value growth.",
      "Onion prices have risen sharply due to a 20% reduction in harvest across major producing states, prompting the government to release buffer stocks to moderate market rates.",
      "Pulse prices are seeing a downward correction after a bumper harvest this season, with government procurement operations helping maintain remunerative price levels for farmers.",
      "The spice market reports steady growth in both export and domestic sectors, with turmeric and cardamom prices reaching five-year highs due to quality improvements and international demand.",
      "Fruit prices are fluctuating significantly due to weather disruptions in key growing regions, with apples and mangoes seeing particular volatility based on production volumes.",
      "Wheat procurement at minimum support price has benefited over 10 million farmers across northern plains, with record quantities purchased by government agencies this season.",
      "Cotton prices have improved substantially as textile industry demand increases post-pandemic, with premium varieties commanding particularly good returns for farmers who maintained quality.",
      "The oilseed market has responded positively to new export opportunities in Southeast Asian countries, with mustard and groundnut farmers seeing significantly better returns this year.",
      "Sugar prices remain relatively stable despite fluctuations in production volumes, with the export quota system and ethanol blending program helping maintain market equilibrium.",
      "Potato farmers are receiving better returns through direct marketing channels established with institutional buyers, reducing dependency on traditional market intermediaries.",
      "Tea auctions across India are reporting increased buyer participation and better prices, particularly for quality grades from Assam and Darjeeling regions that are in high demand.",
      "Maize prices have strengthened considerably as poultry feed demand grows with the expansion of the livestock sector, creating favorable market conditions for corn producers.",
      "Coffee growers are seeing improved profits from specialty market demand, with arabica varieties from high-altitude regions commanding premium prices in international markets.",
      "Milk procurement prices have increased by approximately 10% benefiting dairy farmers across cooperative networks, with the rise attributed to growing demand for value-added dairy products.",
      "The flower market is recovering strongly as wedding season demand picks up, with marigold and rose growers in particular reporting significantly better returns than the previous season.",
      "Jaggery prices remain firm in rural markets across India due to growing consumer preference for natural sweeteners, benefiting sugarcane farmers who process their crop into value-added products.",
      "Organic produce consistently commands a 30% premium in urban markets, with certified vegetables, fruits, and grains finding ready buyers through specialized retail channels and subscription services.",
      "Cashew nut prices have improved substantially after expansion in the domestic processing sector reduced dependency on imported kernels, creating better returns for local growers.",
      "Mango exports to new international destinations have opened additional price discovery channels for growers, with GI-tagged varieties securing particularly advantageous terms in premium markets.",
    ],
    "climate_updates": [
      "The Indian Meteorological Department has forecast normal monsoon rainfall for agricultural regions this year, bringing relief to farmers after last year's uneven precipitation patterns.",
      "A severe heat wave alert has been issued for northern wheat-growing states, with temperatures expected to remain 4-6 degrees above normal during the crucial grain filling stage.",
      "The newly implemented early warning system helped farmers prepare for extreme weather events, with SMS alerts reaching 80% of registered farmers at least 72 hours before severe conditions.",
      "Climate-resilient crop varieties developed by agricultural universities are showing promising results in drought conditions, with yields 25-30% higher than conventional varieties under water stress.",
      "Extensive flood mitigation measures including embankment strengthening and drainage channel clearing have protected farmlands in low-lying areas that were previously vulnerable to monsoon flooding.",
      "Weather pattern analysis reveals a significant shift in traditional growing seasons, with the monsoon onset delayed by an average of 15 days compared to historical data from the past 30 years.",
      "Frost protection advisories have been issued for horticultural regions in northern and central India, with recommendations to use protective covers and smoke treatments for vulnerable crops.",
      "The long-range forecast suggests favorable conditions for Rabi crops with adequate winter precipitation expected in wheat-growing regions and moderate temperatures during the growing season.",
      "Agricultural meteorological stations have been expanded to cover 80% of districts nationwide, providing localized weather data and crop-specific advisories to farming communities.",
      "Research data confirms that climate change is significantly impacting yield variations in rain-fed agricultural zones, with increased frequency of dry spells during critical crop growth stages.",
      "A new hailstorm damage assessment system using mobile photography and AI analysis has been implemented for expediting insurance claims, reducing processing time from weeks to days.",
      "Cyclone early warning systems helped coastal farmers harvest mature crops and secure farm assets before the recent tropical storm, significantly reducing agricultural losses in affected areas.",
      "A heat stress monitoring system guiding irrigation scheduling has been deployed in drought-prone regions, with automated alerts when temperatures cross crop-specific thresholds.",
      "Winter conditions have been particularly favorable for wheat development in North India this year, with adequate chilling hours and soil moisture promising good yields for the season.",
      "Agro-climatic zone mapping has been updated to reflect changing rainfall and temperature patterns, with implications for crop planning and variety selection across different regions.",
      "The weather-based crop advisory system now reaches 60% of the farming population through mobile apps and SMS services, providing timely recommendations based on forecasted conditions.",
      "Dry spell mitigation strategies including protective irrigation and mulching techniques have been shared with farmers in vulnerable regions facing prolonged breaks in monsoon rainfall.",
      "The agricultural phenological calendar has been adjusted to align with observed climate shifts, helping farmers time their planting and harvesting operations according to new seasonal patterns.",
      "Remote sensing data from satellites is being effectively used to assess moisture stress in standing crops across large areas, guiding irrigation interventions during critical growth stages.",
      "Temperature anomaly tracking systems are providing valuable data to guide agricultural planning, with heat-tolerant crop varieties recommended for regions showing warming trends.",
    ],
    "government_schemes": [
      "The 16th installment under the PM Kisan scheme has been released, transferring ₹2,000 directly to the bank accounts of 10 crore farmers nationwide as income support for the agricultural season.",
      "The Soil Health Card scheme has entered a new phase with advanced testing parameters including micronutrient analysis and biological health indicators to provide more comprehensive soil management recommendations.",
      "The electronic National Agriculture Market (e-NAM) platform has expanded to include 1000 agricultural markets nationwide, creating a unified online trading platform for farmers across different states.",
      "Pradhan Mantri Fasal Bima Yojana has covered a record crop area this season, with over 30% of the gross cropped area now under insurance protection against natural calamities and pest outbreaks.",
      "The Agricultural Infrastructure Fund has approved projects worth ₹10,000 crore for developing post-harvest management facilities, cold chains, and primary processing units across rural areas.",
      "The Kisan Credit Card scheme has simplified its renewal process, introducing automatic limit enhancement based on repayment history and removing the requirement for annual paperwork for regular users.",
      "The organic farming certification subsidy has been increased to 90% for small farmers with holdings below 2 hectares, significantly reducing the financial barrier to entering premium organic markets.",
      "A new scheme has been launched to promote natural farming across India, with a target of converting 10% of agricultural land to chemical-free cultivation within the next five years.",
      "Government procurement operations have been extended to additional crops including pulses and oilseeds in 12 states where these crops are major sources of farmer income but previously lacked price support.",
      "The micro-irrigation subsidy scheme has achieved 5 million hectare coverage, with drip and sprinkler irrigation systems improving water use efficiency by 30-50% across different crops and regions.",
      "The farmer producer organization policy has been revised with increased financial support for equity grants and credit guarantee, enabling these farmer collectives to establish viable agribusinesses.",
      "The agricultural mechanization scheme now includes custom hiring centers for farm machinery as a key component, making modern equipment accessible to small and marginal farmers at affordable rates.",
      "Post-harvest management has received a significant boost with a new processing infrastructure scheme that provides 35% capital subsidy for setting up primary processing facilities at the village level.",
      "The agri-clinic and agri-business scheme is creating rural entrepreneurship opportunities, with over 5,000 agricultural graduates establishing service centers in rural areas this year.",
      "The livestock insurance scheme coverage has been expanded to include additional species including goats, sheep, and pigs, providing risk protection to a broader segment of animal husbandry practitioners.",
      "The beekeeping initiative under the ATMA scheme has shown remarkable progress, with 50,000 farmers trained in apiculture and honey production as an additional income stream in rural areas.",
      "The rural godown scheme has been revised with higher subsidy rates to address the critical storage infrastructure gap at the village level, reducing post-harvest losses for small producers.",
      "The marketing infrastructure scheme has funded 500 new rural markets this year, improving farmers' access to market facilities within reasonable distances from production centers.",
      "The integrated scheme for agricultural marketing has improved the value chain for perishable commodities, with a focus on reducing intermediaries and improving farmers' share in consumer prices.",
      "The sub-mission on agricultural mechanization has now reached tribal areas with specially designed implements suitable for hilly terrain and small farm operations in challenging topographies.",
    ],
    "farmer_stories": [
      "A progressive farmer from Tamil Nadu has won the national award for innovative practices after developing a unique multi-crop system that increases land productivity by 40% while conserving water resources.",
      "A women farmers' collective in rural Rajasthan has transformed their village economy by establishing a community-managed food processing unit that adds value to locally grown produce.",
      "Tribal farmers in Northeast India have successfully adopted agroforestry practices that combine traditional knowledge with modern techniques, significantly improving their income while preserving forest biodiversity.",
      "A young agricultural entrepreneur's startup connecting farmers directly to urban consumers has created employment for 50 rural youth while ensuring better prices for local producers.",
      "A veteran farmer with five decades of experience is mentoring youth in his district to adopt sustainable farming techniques, creating a knowledge bridge between traditional wisdom and modern science.",
      "A resourceful farmer from a water-scarce region in Maharashtra has developed an innovative irrigation method using clay pots, reducing water consumption by 60% while maintaining crop yields.",
      "Organic farming has transformed the fortunes of a small farmer collective in Kerala, with their certified produce now commanding premium prices in domestic and international markets.",
      "A self-help group of widow farmers has achieved financial independence through intensive vegetable cultivation, supporting each other through knowledge sharing and collective marketing.",
      "A marginal farmer with just half an acre of land has increased his income threefold by implementing an integrated farming system combining crops, livestock, and fish in a carefully designed layout.",
      "A traditional seed keeper has preserved over 200 indigenous rice varieties for future generations, creating a living seed bank that's now supporting biodiversity conservation efforts across the region.",
      "A farmer-scientist partnership has developed location-specific farming solutions for saline soils in coastal areas, benefiting hundreds of farmers who previously struggled with low productivity.",
      "A rural innovation by a small farmer to solve post-harvest challenges locally has been recognized nationally and is now being replicated in similar agro-climatic zones across multiple states.",
      "A farmer's market initiative directly connecting producers with urban consumers has eliminated intermediaries, resulting in 40% higher income for participating farmers and fresher produce for buyers.",
      "An agricultural influencer educates thousands of farmers through social media platforms, sharing evidence-based practices and indigenous knowledge in accessible regional language videos.",
      "A disabled farmer has overcome significant physical challenges to become a village mentor, developing modified farm tools and techniques that are now helping others with similar conditions.",
      "Landless agricultural laborers in a drought-prone district have formed a cooperative for economic empowerment, collectively leasing land and implementing sustainable farming practices with remarkable success.",
      "A millennial who returned to his village after corporate employment has transformed his family farm into a thriving agribusiness, combining traditional crops with high-value horticulture and agritourism.",
      "Farmer-led watershed development has transformed a previously drought-prone region, with community-managed water harvesting structures improving groundwater levels and agricultural productivity.",
      "A community supported agriculture model in a peri-urban area has successfully connected 50 small farmers with 500 urban households through weekly produce subscriptions, ensuring stable income for producers.",
      "An indigenous knowledge keeper has successfully integrated traditional farming practices with modern techniques, creating a sustainable model that's particularly resilient to climate variations.",
    ],
    "agricultural_exports": [
      "India's agricultural exports have crossed the $50 billion mark for the first time, representing a 20% increase over the previous fiscal year and establishing a new benchmark for the sector.",
      "Basmati rice exports to Middle Eastern countries have increased by 25% this fiscal year, with new quality certifications helping Indian varieties command premium prices in these markets.",
      "Organic food exports from India have seen significant growth in European markets, with certified products including spices, tea, and basmati rice experiencing particularly strong demand.",
      "Indian spices are gaining new markets in Latin America and Africa, with exports to these regions growing at 35% annually as awareness of Indian cuisine and interest in natural seasonings increases globally.",
      "GI-tagged agricultural products from India are commanding premium prices in international markets, with Darjeeling tea, Alphonso mangoes, and Basmati rice being the top performers.",
      "Mango varieties from India have entered new international destinations after successful phytosanitary protocol negotiations, with exports to Australia and South Korea showing promising initial results.",
      "Buffalo meat exports have recovered strongly after pandemic-related disruptions, with shipments to Southeast Asian and Middle Eastern markets returning to pre-pandemic volumes and values.",
      "Marine products export from India has reached an all-time high with a focus on value addition, with processed shrimp and ready-to-cook seafood items finding strong acceptance in international markets.",
      "The Agricultural and Processed Food Export Development Authority has set ambitious new targets for the next five years, focusing on market diversification and value-added product development.",
      "Non-basmati rice shipments continue to grow despite selective export restrictions, with African countries being the largest importers of Indian rice varieties for food security programs.",
      "Fresh fruit exports, particularly of grapes and pomegranates, have benefited from improved cold chain logistics, enabling Indian produce to reach distant markets in excellent condition.",
      "Cereal exports have diversified beyond traditional markets, with millets and sorghum finding new buyers in health-conscious consumer segments across developed economies.",
      "India has become the leading global exporter of specific spice varieties including turmeric, cumin, and coriander, with quality improvements driving value growth in these categories.",
      "Dairy product exports have increased substantially with new quality certifications, with skimmed milk powder and butter finding strong markets in neighboring countries and the Middle East.",
      "Tea exports have benefited from increased demand for specialty varieties including orthodox and green teas, with premium estates developing direct relationships with international buyers.",
      "Agricultural export zones dedicated to specific commodities have shown increased outbound shipments, with the focused approach to infrastructure and quality control yielding positive results.",
      "Honey exports have doubled after the implementation of traceability and quality protocols, with organic and monofloral varieties commanding premium prices in European and North American markets.",
      "Natural food coloring exports derived from agricultural sources like turmeric and beetroot have benefited from the global clean label movement and increasing demand for natural ingredients.",
      "The seeds export program has opened new revenue streams for producers of high-quality planting material, with vegetable and flower seeds finding markets across South and Southeast Asia.",
      "Export promotion schemes specifically designed for small and medium agribusinesses have been particularly successful, helping first-time exporters navigate international market requirements.",
    ],
    "rural_development": [
      "The rural road connectivity program has reached 95% of targeted villages, connecting previously isolated communities to markets, healthcare facilities, and educational institutions.",
      "A digital literacy campaign has transformed information access in rural areas, with community knowledge centers training over 5 million villagers in basic internet skills and agricultural information retrieval.",
      "Self-help groups across rural India have generated record income through agricultural activities this year, with collective farming and food processing emerging as major revenue streams.",
      "A rural entrepreneurship program has created 100,000 new enterprises in villages over the past two years, focusing on agri-allied services, food processing, and handicrafts based on local resources.",
      "The village adoption scheme shows transformative results in pilot areas, with integrated development of agriculture, education, healthcare, and infrastructure creating model rural communities.",
      "The rural housing scheme has completed the milestone of 10 million houses, providing secure and improved living conditions for families previously residing in temporary or dilapidated structures.",
      "Clean energy initiatives including solar pumps and biogas units have benefited agricultural processing in villages, reducing dependency on fossil fuels while creating sustainable energy solutions.",
      "Water conservation structures constructed through community participation have transformed groundwater levels in rural watersheds, with clear improvements in drinking water availability and irrigation potential.",
      "Rural health infrastructure has improved significantly with mobile medical units serving remote areas, bringing diagnostic and primary healthcare services to previously underserved farming communities.",
      "Village knowledge centers equipped with digital resources have boosted agricultural information dissemination, providing farmers with timely advisories on crop management and market conditions.",
      "The rural sanitation campaign has achieved open defecation free status in 125 new districts this year, improving public health conditions and dignity for farming families across these regions.",
      "Financial inclusion has reached 90% of rural households through expanded banking services, with particular focus on credit access for agricultural operations and allied activities.",
      "Women's empowerment through agricultural skilling programs shows remarkable results, with over 200,000 rural women trained in specialized farming techniques and agri-entrepreneurship.",
      "Rural tourism linked with agricultural experiences is generating additional income for farming communities, with 'farm stays' and 'harvest festivals' attracting urban visitors seeking authentic rural experiences.",
      "Digital service centers in villages have simplified access to government programs, with over 100 million farmers now able to apply for schemes and subsidies without traveling to distant administrative offices.",
      "Rural artisans have found new markets through e-commerce platforms specializing in handcrafted products, connecting traditional craft skills with contemporary urban consumers.",
      "Community-managed natural resource initiatives focusing on forest protection and regeneration show sustainable outcomes, with improved biodiversity and non-timber forest product availability.",
      "Rural sports infrastructure development in agricultural communities has nurtured young talent, with several national-level athletes emerging from farming families in previously overlooked regions.",
      "Traditional crafts linked with agricultural byproducts like bamboo, jute, and cotton have created employment opportunities for rural youth, combining heritage skills with modern design sensibilities.",
      "Rural technology hubs are connecting villages to knowledge resources, with innovation centers established in agricultural districts to develop locally relevant solutions for farming challenges.",
    ],
    "organic_farming": [
      "The area under certified organic farming in India has expanded by 25% in the past year, with more farmers transitioning from conventional practices due to increasing market demand and premium prices.",
      "Sikkim's successful model as a fully organic state is being replicated in other Himalayan states including Uttarakhand and Himachal Pradesh, with government support for the transition process.",
      "Natural farming practices that minimize external inputs have reduced production costs for small farmers by up to 40%, while maintaining comparable yields after the initial transition period.",
      "The organic certification process has been simplified for farmer groups through the Participatory Guarantee System, making verification more accessible and affordable for small producers.",
      "Market linkages for organic produce have strengthened with dedicated supply chains connecting certified farmers to urban retail outlets, institutional buyers, and export markets.",
      "Organic farming training programs have reached 100,000 farmers nationwide through a cascade model where master trainers educate community-level resource persons who then train local farmers.",
      "Zero budget natural farming techniques are showing promising results in rain-fed areas, with farmers reporting improved resilience to drought conditions and reduced dependency on credit for inputs.",
      "The use of indigenous microorganisms in organic systems has significantly improved soil health parameters, with measurable increases in organic carbon content and microbial activity.",
      "The organic villages initiative has successfully created chemical-free agricultural zones in over 500 locations nationwide, with entire communities adopting sustainable farming methods.",
      "The Participatory Guarantee System for organic certification has made verification accessible to small farmers, with 200,000 producers now certified through this community-based approach.",
      "Research conducted across organic farming regions documents significant biodiversity improvement, with increased pollinator populations and beneficial insects returning to agricultural landscapes.",
      "Traditional knowledge of organic practices including pest management, seed treatment, and crop rotation has been systematically documented and shared through farmer field schools.",
      "Growing urban demand for organic produce has created premium market opportunities, with organic farmers receiving 20-30% higher prices compared to conventional products in metro cities.",
      "Organic seed production networks have established self-sufficiency in several states, preserving indigenous varieties while ensuring chemical-free planting material for organic farmers.",
      "Integrated organic farming systems combining crops, livestock, and recycling components optimize resource utilization, with models developed for different land holding sizes and agro-climatic zones.",
      "Weekly organic farmers' markets have established direct connections between producers and consumers in 50 cities, eliminating intermediaries while building relationships based on transparency and trust.",
      "Organic input production units have been set up at the panchayat level in major agricultural states, enabling local production of biofertilizers, botanical pesticides, and other essential materials.",
      "Export demand for certified organic products continues to grow at 15% annually, with spices, tea, and basmati rice being particularly sought after in international markets.",
      "Organic farming adoption has successfully addressed soil health concerns in regions previously affected by chemical deterioration, with measurable improvements in structure and fertility over time.",
      "Training modules on organic farming practices have been translated into 15 regional languages, making technical knowledge accessible to farmers across different linguistic regions.",
    ],
    "farm_mechanization": [
      "Custom hiring centers for farm machinery have reached every district, making advanced equipment accessible to small farmers at affordable hourly rates without requiring capital investment.",
      "Specially designed small farm mechanization tools have been developed for hilly terrain, addressing the unique challenges of farming on slopes and in terraced fields across mountainous regions.",
      "Solar-powered agricultural equipment including water pumps, weeders, and small threshers are gaining popularity in field operations, reducing dependency on fossil fuels while cutting operational costs.",
      "Women-friendly farm tools designed with appropriate ergonomics are addressing gender-specific challenges in agriculture, reducing drudgery and improving efficiency in tasks predominantly performed by women.",
      "Drone adoption for agricultural operations has expanded with new regulatory support, enabling aerial spraying, crop monitoring, and precision applications in large fields and difficult terrain.",
      "Precision planting equipment that ensures optimal seed placement and spacing is improving germination rates and early crop establishment, resulting in better stands and higher yields.",
      "New harvester modifications specifically address crop residue management challenges, with attachments that effectively mulch and spread straw to eliminate the need for stubble burning.",
      "Farm mechanization subsidy utilization has reached record levels this year, with 200,000 farmers accessing financial support for purchasing equipment ranging from power tillers to combine harvesters.",
      "Locally manufactured agricultural tools based on indigenous designs have reduced equipment costs while ensuring appropriateness for local conditions and ease of maintenance in rural areas.",
      "Multi-crop planters and harvesters capable of handling different grains, oilseeds, and pulses are gaining popularity among farmers practicing crop diversification and rotation systems.",
      "Mechanized transplanting of rice using specialized machines has significantly reduced labor requirements while improving plant spacing and establishment, resulting in better yields.",
      "Post-harvest mechanization including cleaners, graders, and primary processors has reduced grain losses by up to 30%, improving both quantity and quality of marketable produce.",
      "Small tractors specifically designed for marginal landholdings under 2 hectares have increased operational efficiency while being affordable for small farmers through group ownership models.",
      "Digital platforms for machinery rental have transformed equipment access in rural areas, with mobile apps connecting equipment owners with farmers seeking specific implements for short durations.",
      "Training programs on equipment maintenance have reached grassroot mechanics in rural areas, creating local expertise for servicing and repairing agricultural machinery at the village level.",
      "Laser land leveling technology adoption has improved water use efficiency by 20-30%, with one-time investment in field preparation resulting in long-term benefits for irrigation management.",
      "Machinery banks established at farmer producer organization level have made a wide range of equipment available to member farmers, with scheduled sharing systems ensuring timely access during peak seasons.",
      "Indigenous innovation in farm tools has addressed specific local agricultural needs, with farmer-designed implements manufactured by rural workshops gaining popularity in their regions.",
      "Specialized fruit harvesting equipment that reduces damage and improves quality has been widely adopted in horticultural regions, reducing post-harvest losses while improving market value.",
      "Virtual reality training modules are preparing equipment operators for complex machinery operation, with simulation-based learning reducing accidents and improving operational efficiency.",
    ],
    "agriculture_education": [
      "Agricultural universities across India have revamped their curriculum to include emerging technologies such as precision farming, artificial intelligence applications, and biotechnology in agriculture.",
      "Vocational agriculture courses are seeing increased enrollment across rural areas, with practical skill-based training preparing youth for both farm management and agribusiness opportunities.",
      "Krishi Vigyan Kendras have trained a record number of farmers in new techniques this year, with hands-on demonstrations and field trials making scientific innovations accessible at the local level.",
      "Digital learning platforms specialized in agricultural content have made education accessible remotely, with over 2 million farmers utilizing online courses and video lessons on improved practices.",
      "School garden programs have been introduced in 5,000 rural schools, familiarizing students with sustainable farming practices and nutrition concepts while supplying fresh produce for mid-day meals.",
      "A new agricultural apprenticeship program is connecting recent graduates with progressive farms, providing practical experience that bridges theoretical knowledge with real-world application.",
      "International collaboration between Indian and global agricultural universities has strengthened research and education, with exchange programs benefiting both students and faculty members.",
      "Industry-academia partnerships have created clear employment pathways for agricultural graduates, with companies participating in curriculum design and offering internship opportunities.",
      "Farmers' field schools demonstrating improved practices have been established in 10,000 villages, using peer learning approaches to disseminate knowledge about sustainable techniques.",
      "Agri-clinics established by agricultural graduates provide knowledge services to farming communities, with expert advice on crop health, input management, and market information readily available.",
      "Mobile agricultural extension classrooms housed in specially equipped vehicles are reaching remote farming communities, bringing training programs and demonstrations to isolated villages.",
      "Skill certification programs are validating traditional agricultural knowledge, providing formal recognition for indigenous practices and experienced practitioners in rural communities.",
      "Agricultural hackathons have successfully engaged youth in solving farming challenges, with innovative solutions for water management, pest detection, and market linkage emerging from these events.",
      "Rural agricultural libraries have expanded their digital resources, with tablets and e-readers loaded with farming information making knowledge accessible even in areas with limited connectivity.",
      "A comprehensive training of trainers program has created 10,000 master farmers who serve as local educators, disseminating scientific knowledge while incorporating contextual understanding of local conditions.",
      "Agri-business education programs specifically designed to nurture rural entrepreneurship have trained 50,000 youth in market assessment, business planning, and value chain development.",
      "Distance learning programs in agriculture now reach working professionals across rural areas, allowing farmers to upgrade their knowledge while continuing their agricultural activities.",
      "Regular farmer-scientist interaction platforms facilitate knowledge exchange, with researchers gaining insights about field challenges while farmers learn about scientific innovations and solutions.",
      "Agricultural podcasts in regional languages have gained a substantial rural listenership, with episodic content on seasonal farming operations delivered through mobile phones reaching 5 million farmers.",
      "Specialized training centers focusing on emerging agricultural sectors such as protected cultivation, processing technologies, and export compliance have been established in major agricultural zones.",
    ],
    "livestock_farming": [
      "An indigenous cattle breeding program has made significant progress in preserving native genetic resources, with registrations of pure breeds increasing by 30% in the past year alone.",
      "Dairy cooperatives have expanded their milk collection network to previously underserved areas, bringing 500,000 new producers into the organized dairy sector with guaranteed procurement.",
      "Innovative poultry farming models specifically designed for landless agricultural laborers are providing sustainable livelihoods, with backyard units requiring minimal space and investment.",
      "Goat farming initiatives have transformed livelihoods in drought-prone regions, with hardy local breeds proving resilient to climate challenges while providing regular income through meat and milk.",
      "Animal health cards have been implemented for livestock monitoring and management, with digital records of vaccination, treatment, and breeding history accessible through QR codes.",
      "A comprehensive fodder development program is addressing nutritional challenges in livestock by promoting high-yielding fodder varieties and conservation methods for year-round availability.",
      "Backyard poultry initiatives have successfully improved protein nutrition in rural households while generating supplementary income, with improved native breeds distributed to 1 million families.",
      "Veterinary telemedicine services now reach remote pastoral communities, connecting livestock keepers with specialists for diagnosis and treatment advice through video consultations.",
      "A sheep wool quality improvement program has benefited traditional herders through breeding enhancement and better shearing practices, resulting in higher value for the wool produced.",
      "The indigenous poultry breeds conservation program has gained momentum with community participation, preserving valuable genetic resources while promoting these birds for niche markets.",
      "Camel dairy initiatives in arid regions are creating new livelihood opportunities, with processing units for camel milk products establishing viable value chains for pastoral communities.",
      "Pig farming enterprises have shown remarkable success in tribal areas with proper training and support, providing significant income through improved breeds and scientific management practices.",
      "Mobile veterinary units have extended coverage to remote livestock rearing areas, providing essential health services to animals that previously had limited access to professional care.",
      "Fish farming in farm ponds demonstrates an effective integrated livelihood model, utilizing irrigation water bodies for additional protein production and income generation.",
      "The vaccine delivery system for livestock has been significantly strengthened, with cold chain infrastructure ensuring that preventive healthcare reaches animals even in remote villages.",
      "Breeding records digitization is helping maintain comprehensive genetic improvement data, with artificial insemination centers now tracking outcomes and progeny performance systematically.",
      "Silage making technologies adapted for small-scale production have been widely adopted for year-round fodder availability, addressing seasonal scarcity during summer months and droughts.",
      "Quality milk production initiatives emphasizing clean handling practices and quick chilling have improved dairy farm economics by reducing rejection rates and accessing premium markets.",
      "Innovative waste-to-wealth models are converting livestock waste to valuable byproducts including biogas, organic fertilizer, and vermicompost, creating additional revenue streams for farmers.",
      "Heat stress management protocols developed for livestock protection during extreme summer conditions have reduced productivity losses and mortality, particularly in high-yielding dairy animals.",
    ],
    "irrigation_news": [
      "Micro-irrigation coverage has expanded to 50% of the targeted area nationwide, with drip and sprinkler systems significantly reducing water consumption while improving yield in horticultural crops.",
      "A major canal modernization project has improved water use efficiency in command areas by lining channels and implementing automated distribution systems, benefiting 2 million hectares.",
      "Participatory irrigation management has transformed water distribution equity in large projects, with farmer committees taking responsibility for scheduling and maintenance at the tertiary canal level.",
      "Water user associations have successfully taken charge of irrigation scheduling in 500 projects, reducing conflicts while ensuring fair distribution based on cropping patterns and soil types.",
      "Irrigation infrastructure has received an investment boost through a special package worth ₹25,000 crore, focusing on completing long-pending projects and modernizing existing networks.",
      "Sensor-based irrigation systems that monitor soil moisture in real-time have reduced water consumption by 30% while maintaining or improving yields across different crops and regions.",
      "The river linking project has made significant progress in addressing regional water imbalances, with construction beginning on three major links that will transfer surplus water to deficit basins.",
      "A national check dam construction drive has completed 10,000 structures this year, creating water storage capacity for supplementary irrigation while recharging groundwater in watershed areas.",
      "The farm pond program has created water security for rain-fed agriculture, with 500,000 new ponds constructed to harvest rainfall and provide critical irrigation during dry spells.",
      "Solar pumping systems have replaced diesel pumps in a major irrigation initiative, reducing operating costs for farmers while decreasing carbon emissions from agricultural operations.",
      "A newly developed water budgeting app is helping farmers optimize irrigation scheduling based on crop water requirements and available resources, preventing both deficit and excess application.",
      "Traditional water harvesting structures including step wells and tanks have been revitalized through community efforts, combining ancestral wisdom with modern engineering for sustainable water management.",
      "Drip irrigation adoption for sugarcane cultivation has reduced water usage by 40% while improving yields, with over 200,000 hectares of this water-intensive crop now under precision irrigation.",
      "Irrigation pipeline networks replacing open channels have minimized transit losses, with underground distribution systems preventing evaporation and seepage in major command areas.",
      "Watershed development programs integrating soil and water conservation measures show remarkable groundwater improvement, with water table rises of 1-2 meters documented in treated areas.",
      "Treated wastewater is being increasingly utilized for peri-urban agricultural irrigation, with safety protocols and monitoring systems ensuring appropriate use for different crop categories.",
      "Sprinkler system adoption has increased significantly in water-scarce regions, with portable and semi-permanent setups providing efficient irrigation for closely spaced crops on undulating terrain.",
      "Canal automation technology using gates and sensors has improved distribution efficiency in major irrigation projects, ensuring timely water delivery according to crop growth stages.",
      "Rainwater harvesting structures have been made mandatory for receiving farm infrastructure support, with 200,000 new harvesting systems constructed on agricultural lands this year.",
      "Groundwater recharge initiatives including percolation tanks and injection wells show positive results in over-exploited areas, with monitoring data confirming water level improvements in critical zones.",
    ],
    "agricultural_research": [
      "A gene editing breakthrough achieved by Indian scientists has significantly improved rice drought tolerance, with field trials showing 35% better yields under water-stressed conditions.",
      "The Indian Agricultural Research Institute has released 10 new crop varieties this year, including heat-tolerant wheat, blast-resistant rice, and high-protein pulses suited to different agro-climatic zones.",
      "Climate-resilient crop varieties developed through participatory breeding involve farmers in selection processes, combining scientific techniques with traditional knowledge for locally adapted solutions.",
      "Research on nano-fertilizers has shown promising results in field trials, with these advanced formulations improving nutrient use efficiency by 30% while reducing environmental impacts from leaching.",
      "Biological control agents developed for major crop pests have successfully reduced pesticide use by 40% in demonstration plots, with mass production protocols established for wide-scale adoption.",
      "Genomic selection techniques have accelerated livestock breeding progress, with marker-assisted programs reducing the time required for genetic improvement in native cattle and buffalo breeds.",
      "Long-term research on conservation agriculture documents significant soil health benefits, with 10-year data showing improved organic carbon levels, water retention, and microbial activity in no-till systems.",
      "Crop modeling using advanced algorithms helps predict yield under changing climate scenarios, enabling policy makers and farmers to plan adaptation strategies based on projected conditions.",
      "Integrated pest management strategies have been developed for emerging pests including fall armyworm, with biological, cultural, and limited chemical interventions showing effective control.",
      "Nutrition-sensitive agriculture research has focused on biofortified crops, with high-zinc rice, iron-rich pearl millet, and protein-enhanced chickpea varieties released for addressing malnutrition.",
      "Indigenous technical knowledge collected from farming communities has been scientifically validated through controlled studies, confirming the efficacy of traditional practices for pest management and soil health.",
      "Plant growth promoting rhizobacteria isolated from Indian soils are improving nutrient use efficiency in major crops, with bio-inoculants developed for different agro-climatic conditions.",
      "Post-harvest processing research has successfully reduced food waste by developing appropriate technologies for small-scale operations, extending shelf life for perishable commodities.",
      "New phenomics facilities established at research institutes are accelerating crop improvement by precisely measuring plant responses to environmental stresses using advanced imaging and sensing technologies.",
      "Agri-waste utilization research has created valuable byproducts from crop residues, with processes developed for converting rice straw to packaging materials and sugarcane bagasse to biofuels.",
      "Salt-tolerant crop varieties specially bred for coastal agricultural areas are showing promising performance, enabling cultivation in lands previously affected by seawater intrusion.",
      "Drought-escaping crop varieties with shorter duration cycles are minimizing climate risk for farmers in rain-fed areas, maturing before the typical onset of water stress conditions.",
      "Agricultural biotechnology research has successfully focused on reducing input requirements, with nitrogen-efficient cereals and pest-resistant vegetables requiring fewer chemical applications.",
      "Precision agriculture research using remote sensing and IoT devices is optimizing resource use in farming, with variable rate application technologies demonstrating 25% reduction in input costs.",
      "Crop wild relatives collected from diverse ecosystems are providing valuable traits for breeding programs, with genes for stress tolerance and pest resistance integrated into cultivated varieties.",
    ],
  };
  
  // Generate random news items based on category
  const news = [];
  const titles = categoryTitles[category] || categoryTitles.general_agriculture;
  const summaries = categorySummaries[category] || categorySummaries.general_agriculture;
  
  const usedIndices = new Set();
  
  while (news.length < count && usedIndices.size < titles.length) {
    // Get random index that hasn't been used yet
    let randomIndex;
    do {
      randomIndex = Math.floor(Math.random() * titles.length);
    } while (usedIndices.has(randomIndex));
    
    usedIndices.add(randomIndex);
    
    news.push({
      title: titles[randomIndex],
      summary: summaries[randomIndex],
      source: newsSources[Math.floor(Math.random() * newsSources.length)],
      publishedAt: generateRecentDate(),
      category: category,
      readTime: generateReadTime(),
      url: "#" // Placeholder URL
    });
  }
  
  return news;
};

// Generate headlines for the ticker tape
const generateHeadlines = (allNews: any[], count: number = 8) => {
  // Shuffle the news array and take the first 'count' items for headlines
  const shuffled = [...allNews].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count).map(item => item.title);
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    let { category } = await req.json();
    
    // Default to general_agriculture if no category is specified
    if (!category) {
      category = "general_agriculture";
    }
    
    // Generate news for the requested category
    const news = generateNewsForCategory(category);
    
    // Generate headlines from across all categories for ticker
    const allCategories = [
      "general_agriculture", "crop_production", "agritech", 
      "market_prices", "climate_updates", "government_schemes"
    ];
    
    let allNews: any[] = [];
    allCategories.forEach(cat => {
      // Get just a few news items from each category for headlines
      const categoryNews = generateNewsForCategory(cat, 3);
      allNews = [...allNews, ...categoryNews];
    });
    
    const headlines = generateHeadlines(allNews);
    
    // Return the news data
    return new Response(JSON.stringify({
      news,
      category,
      headlines,
      generatedAt: new Date().toISOString()
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Error in get-agri-news function:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
